### ISSUE TITLE
Update coffee-react dependency

### ISSUE THREAD

**Issue by dennismphil** [jsifalda/coffee-jsx-loader#4]
`coffee-react` has a `5.0.0` release. 

Please update the `"coffee-react": "^4.0.0"` dependency

**Comment by jsifalda** [comment]
PR?

**Comment by dennismphil** [comment]
Done. Can you publish `0.1.4` to npm please?

**Comment by jsifalda** [comment]
Published https://www.npmjs.com/package/coffee-jsx-loader
